### ISSUE TITLE
r&d: faceswapping tool

### ISSUE THREAD

**Issue by Matesanz** [Matesanz/junction-move38#2]
# Goal

 Document solutions for face swapping

**Comment by smulaboughaba** [comment]
### **APIs de Faceswapping**

**DeepFaceLab: No he encontrado una api en si pero basicamente hay una libreria en python de estos la cual hace que podamos hacerlo en un codigo que se a muy breve sin tener que consumir muchos recursos.**

DeepFaceLab no tiene una API oficial. Sin embargo, hay algunas librerías de Python que permiten usar DeepFaceLab desde código. Una de estas librerías es DeepFaceLabAPI, que se encuentra en GitHub.

**FaceSwapGAN : pasa lo mismo que la anterior, no tiene api en si pero tiene librería de python (import faceswapgan )**

**FaceSwapMater : Si tiene una API; (pip install faceswapmaster-api )
y se puede aplicar en  el codigo importando la librería , o si se quiere pues
hacerlo en el servidor de ellos creandose una cuenta, obtener una api key y luego en el codigo implementarlo para que ellos me haga en porceso de compilacion.**

**HeyGen's Face Swap API ;  Permite Cambiar caras tanto en videos como en fotos , aqui dejo el enlace de su explicacion https://docs.heygen.com/docs/create-faceswap-image-and-video**

**Replicate : Personalmente me parece la mas clara y concisa a la hora de poder implementarla nosotros en el proyecto, ya que lo que explica de forma concisa como usar su api para implementarla en nuestro codigo. Hay que ver si el pricing y el tiempo que tarde en hacer el proceso nos sirva.
https://replicate.com/lucataco/faceswap/api**

**Faceswap: Es la plataforma de codigo abierto de  Deepfake software  lider del mercado
https://faceswap.dev/**

### **GITHUB**

**ROOP Face Swapper API version**    (https://github.com/lvalics/roopapi)

 **face_swap web API built using python flask**     (https://github.com/GangulliGanesh/Face_Swap)

**Python Flask API for Face Swapper and Restoration powered by insightface**
(https://github.com/ashleykleynhans/inswapper-flask-api)

**Para deteccion de rostro en google usando su api  de vision**
(https://cloud.google.com/vision/docs/face-tutorial?hl=es-419#python)

**cambio de cara conla api de reconocimiento facial de  opencv , con cascade**
(https://github.com/snsurajnath/Face-swap-using-python)

**api que permite añadir un faceswapping  queries a  un  servidor.**
(https://github.com/sp1d5r/identity-matrix/tree/main/app)
